routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('/list', 'RoadTaxController');

Route::resource('/lists', 'RoadTaxListController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/road_tax.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class road_tax extends Model
{
    //
    protected $connection = 'postgres';

    //protected $table = 'road_taxes';
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/RoadTaxController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\road_tax;

class RoadTaxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $road_taxes = road_tax::all();

        return view('roadtaxlist', [
            'road_taxes' => $road_taxes,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/RoadTaxListController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
//use App\road_taxes;
use DB;

class RoadTaxListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
            //
        public function index(Request $request)
        {
         if(request()->ajax())
         {
          if(!empty($request->from_date))
          {
           $data = DB::table('road_taxes')
             ->whereBetween('payment_date', array($request->from_date, $request->to_date))
             ->get();
          }
          else
          {
           $data = DB::table('road_taxes')
             ->get();
          }
          return datatables()->of($data)->make(true);
         }
         return view('roadtaxlists');
        }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/roadtaxlist.blade.php
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>

<br><br>
<div class="container">	
	<h1>Road Tax Report</h1>
	<br><br>
</div>

<div class="container">
     <form>
         <section>
             <div class="panel panel-footer" >
                 <table class="table table-bordered">
                     <thead>
                         <tr align="center">
                             <th>ID</th>
                             <th>Serial Number</th>
                             <th>License Plate</th>
                             <th>Province</th>
                             <th>Purpose</th>
                             <th>Vehicle Type</th>
                             <th>Engine CC</th>
                             <!-- <th>Weight</th> -->
                             <th>Fiscal Year</th>
                             <!-- <th>Road Fee</th> -->
                             <th>Payment Date</th>
                             <!-- <th>Receipt</th> -->
                         </tr>
                     </thead>
                     <tbody>
         @foreach ($road_taxes as $road_tax)
         <tr>
         <td align="center">{{ $road_tax->id }}</td>
         <td align="center">{{ $road_tax->serial_number }}</td>   
         <td align="center">{{ $road_tax->license_plate_number }}</td>
         <td align="center">{{ $road_tax->province }}</td>
         <td align="center">{{ $road_tax->purpose }}</td>   
         <td align="center">{{ $road_tax->vehical_type }}</td>
         <td align="center">{{ $road_tax->engine_cc }}</td>
         <td align="center">{{ $road_tax->fiscal_year }}</td>
         <td align="center">{{ $road_tax->payment_date }}</td>   
         <!-- <td align="center">
            <a href="" class="btn btn-success"> ດັດແກ້ </a>
            <a href="" class="btn btn-danger"> ລົບ </a>
         </td> -->
         </tr>
         @endforeach
                     </tbody>
                 </table>
             </div>
         </section>
     </form>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

resources/views/roadtaxlists.blade.php
<html>
 <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Road Tax Report</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>  
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
 </head>
 <body>
  <div class="container">    
     <br />
     <h3 align="center">Road Tax Report</h3>
     <br />
            <br />
            <div class="row input-daterange">
                <div class="col-md-4">
                    <input type="text" name="from_date" id="from_date" class="form-control" placeholder="From Date" readonly />
                </div>
                <div class="col-md-4">
                    <input type="text" name="to_date" id="to_date" class="form-control" placeholder="To Date" readonly />
                </div>
                <div class="col-md-4">
                    <button type="button" name="filter" id="filter" class="btn btn-primary">Filter</button>
                    <button type="button" name="refresh" id="refresh" class="btn btn-default">Refresh</button>
                </div>
            </div>
            <br />
   <div class="table-responsive">
    <table class="table table-bordered table-striped" id="order_table">
           <thead>
            <tr>
              <th>ID</th>
              <th>Serial Number</th>
              <th>License Plate</th>
              <th>Province</th>
              <th>Purpose</th>
              <th>Vehicle Type</th>
              <th>Engine CC</th>
              <!-- <th>Weight</th> -->
              <th>Fiscal Year</th>
              <!-- <th>Road Fee</th> -->
              <th>Payment Date</th>
              <!-- <th>Receipt</th> -->
            </tr>
           </thead>
       </table>
   </div>
  </div>
 </body>
</html>

<script>
$(document).ready(function(){
 $('.input-daterange').datepicker({
  todayBtn:'linked',
  format:'yyyy-mm-dd',
  autoclose:true
 });

 load_data();

 function load_data(from_date = '', to_date = '')
 {
  $('#order_table').DataTable({
   processing: true,
   serverSide: true,
   ajax: {
    url:'{{ route("lists.index") }}',
    data:{from_date:from_date, to_date:to_date}
   },
   columns: [
    {
     data:'id',
     name:'id'
    },
    {
     data:'serial_number',
     name:'serial_number'
    },
    {
     data:'license_plate_number',
     name:'license_plate_number'
    },
    {
     data:'province',
     name:'province'
    },
    {
     data:'purpose',
     name:'purpose'
    },
    {
     data:'vehical_type',
     name:'vehical_type'
    },
    {
     data:'engine_cc',
     name:'engine_cc'
    },
    {
     data:'fiscal_year',
     name:'fiscal_year'
    },
    {
      data:'payment_date',
      name:'payment_date'
    }
   ]
  });
 }

 $('#filter').click(function(){
  var from_date = $('#from_date').val();
  var to_date = $('#to_date').val();
  if(from_date != '' &&  to_date != '')
  {
   $('#order_table').DataTable().destroy();
   load_data(from_date, to_date);
  }
  else
  {
   alert('Both Date is required');
  }
 });

 $('#refresh').click(function(){
  $('#from_date').val('');
  $('#to_date').val('');
  $('#order_table').DataTable().destroy();
  load_data();
 });

});
</script>